name: '17'
timestamp: 1506805967
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1506208974
positions:
  service: Service
  webproject: Webproject
  portfolio: Portfolio
  team: Team
  number: Number
  info: Info
  form: Form
sections:
  top: Topo
  social: Social
  slider: SlideShow
  service: Serviços
  web-project: 'Projetos Web'
  portfolio: Portfolio
  team: Equipe
  number: Números
  contact: Contato
  footer: Rodapé
  offcanvas: Offcanvas
particles:
  logo:
    logo-5846: Logo
  menu:
    menu-4167: Menu
  social:
    social-1836: Social
  slider:
    slider-4260: Slider
  position:
    position-service: Service
    position-webproject: Webproject
    position-portfolio: Portfolio
    position-team: Team
    position-number: Number
    position-info: Info
    position-form: Form
  branding:
    branding-9985: Branding
  totop:
    totop-6026: Totop
  copyright:
    copyright-2097: Copyright
  mobile-menu:
    mobile-menu-1056: 'Mobile Menu'
inherit: {  }
