name: '17'
timestamp: 1503688699
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1503688640
positions:
  slider: Slider
  service: Service
  webproject: Webproject
  portfolio: Portfolio
  team: Team
  number: Number
  info: Info
  form: Form
sections:
  top: Topo
  social: Social
  slider: SlideShow
  service: Serviços
  web-project: 'Projetos Web'
  portfolio: Portfolio
  team: Equipe
  number: Números
  contact: Contato
  footer: Rodapé
  offcanvas: Offcanvas
particles:
  logo:
    logo-1341: Logo
  menu:
    menu-5594: Menu
  social:
    social-6649: Social
  position:
    position-slider: Slider
    position-service: Service
    position-webproject: Webproject
    position-portfolio: Portfolio
    position-team: Team
    position-number: Number
    position-info: Info
    position-form: Form
  branding:
    branding-7795: Branding
  totop:
    totop-5042: Totop
  copyright:
    copyright-4274: Copyright
  mobile-menu:
    mobile-menu-9957: 'Mobile Menu'
inherit: {  }
