name: '17'
timestamp: 1507762583
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1507762475
positions:
  portfolio: Portfolio
  team: Team
  number: Number
  info: Info
  form: Form
sections:
  top: Topo
  social: Social
  slider: SlideShow
  service: Serviços
  web-project: 'Projetos Web'
  portfolio: Portfolio
  team: Equipe
  number: Números
  contact: Contato
  footer: Rodapé
  offcanvas: Offcanvas
particles:
  logo:
    logo-2076: Logo
  menu:
    menu-7386: Menu
  social:
    social-5703: Social
  slider:
    slider-2904: Slider
  service:
    service-5249: Service
  webproject:
    webproject-5636: Webproject
  position:
    position-portfolio: Portfolio
    position-team: Team
    position-number: Number
    position-info: Info
    position-form: Form
  branding:
    branding-1577: Branding
  totop:
    totop-5988: Totop
  copyright:
    copyright-8518: Copyright
  mobile-menu:
    mobile-menu-9282: 'Mobile Menu'
inherit: {  }
