name: 17
timestamp: 1501715652
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1501715651
positions:
  slider: Slider
  service: Service
  webproject: Webproject
  portfolio: Portfolio
  team: Team
  number: Number
  info: Info
  form: Form
sections:
  top: Topo
  slider: SlideShow
  service: Serviços
  web-project: 'Projetos Web'
  portfolio: Portfolio
  team: Equipe
  number: Números
  contact: Contato
  footer: Rodapé
  offcanvas: Offcanvas
particles:
  logo:
    logo-1982: Logo
  menu:
    menu-7131: Menu
  social:
    social-7880: Social
  position:
    position-slider: Slider
    position-service: Service
    position-webproject: Webproject
    position-portfolio: Portfolio
    position-team: Team
    position-number: Number
    position-info: Info
    position-form: Form
  branding:
    branding-5351: Branding
  totop:
    totop-1814: Totop
  copyright:
    copyright-5421: Copyright
  mobile-menu:
    mobile-menu-1101: 'Mobile Menu'
inherit: {  }
