version: 2
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1507762475
layout:
  /top/:
    -
      - 'logo-2076 30'
      - 'menu-7386 70'
  /social/:
    -
      - social-5703
  /slider/:
    -
      - slider-2904
  /service/:
    -
      - service-5249
  /web-project/:
    -
      - webproject-5636
  /portfolio/:
    -
      - position-portfolio
  /team/:
    -
      - position-team
  /wrapper-bottom/:
    /number/:
      -
        - position-number
    /contact/:
      -
        - 'position-info 50'
        - 'position-form 50'
  /footer/:
    -
      - 'branding-1577 33.3'
      - 'totop-5988 33.3'
      - 'copyright-8518 33.3'
  offcanvas:
    -
      - mobile-menu-9282
structure:
  top:
    type: section
    subtype: header
    title: Topo
    attributes:
      boxed: ''
  social:
    type: section
    attributes:
      boxed: '3'
  slider:
    type: section
    title: SlideShow
    attributes:
      boxed: ''
  service:
    type: section
    title: Serviços
    attributes:
      boxed: ''
  web-project:
    type: section
    title: 'Projetos Web'
    attributes:
      boxed: ''
  portfolio:
    type: section
    attributes:
      boxed: ''
  team:
    type: section
    title: Equipe
    attributes:
      boxed: ''
  number:
    type: section
    title: Números
    attributes:
      boxed: ''
  contact:
    type: section
    title: Contato
    attributes:
      boxed: ''
  wrapper-bottom:
    attributes:
      name: Wrapper
      boxed: ''
  footer:
    title: Rodapé
    attributes:
      boxed: ''
content:
  logo-2076:
    block:
      class: wa-logo
  menu-7386:
    block:
      class: wa-menu
  social-5703:
    attributes:
      display: icons_only
      items:
        -
          icon: 'fa fa-twitter'
          text: Twitter
          link: 'http://twitter.com/leowg'
          name: Twitter
        -
          icon: 'fa fa-facebook'
          text: Facebook
          link: 'http://facebook.com/leowgweb'
          name: Facebook
        -
          icon: 'fa fa-google'
          text: Google
          link: 'http://plus.google.com/+leowgweb'
          name: Google
        -
          icon: 'fa fa-youtube'
          text: Youtube
          link: 'http://www.youtube.com/leowgweb'
          name: Youtube
    block:
      class:
        - 'wa-social hidden-phone'
      variations:
        - 'nopaddingall nomarginall'
  slider-2904:
    attributes:
      title1: 'Descubra a Verdadeira Essência do Seu Projeto'
      title2: 'Criatividade, Simplicidade e Inovação'
      title3: 'Deixe um brilho nos olhos de seus clientes ao apreciarem seu Projeto'
      imageOverlay: 'gantry-media://slider-particle/image-overlay.png'
      overlay: 'gantry-theme://js/vegas-background-slideshow/overlays/01.png'
      transition: fade
      animation: kenburns
      delay: 5000
      transitionDuration: auto
      animationDuration: auto
      images:
        -
          title: 'Imagem 1'
          image: 'gantry-media://slider-particle/image1.jpg'
        -
          title: 'Imagem 2'
          image: 'gantry-media://slider-particle/image2.jpg'
        -
          title: 'Imagem 3'
          image: 'gantry-media://slider-particle/image3.jpg'
  service-5249:
    attributes:
      headline: 'Nossos Serviços'
      services:
        -
          icon: 'fa fa-laptop'
          title: 'Web Sites'
          description: 'It is a long established fact that a reader will be distracted by the looking at its '
        -
          icon: 'fa fa-opencart'
          title: 'Lojas Virtuais'
          description: 'It is a long established fact that a reader will be distracted by the looking at its '
        -
          icon: 'fa fa-sitemap'
          title: 'Hot Sites'
          description: 'It is a long established fact that a reader will be distracted by the looking at its '
        -
          icon: 'fa fa-connectdevelop'
          title: 'Sistemas Web'
          description: 'It is a long established fact that a reader will be distracted by the looking at its '
        -
          icon: 'fa fa-android'
          title: Apps
          description: 'It is a long established fact that a reader will be distracted by the looking at its '
        -
          icon: 'fa fa-at'
          title: 'E-mail Marketing'
          description: 'It is a long established fact that a reader will be distracted by the looking at its '
    block:
      variations: title1
  webproject-5636:
    attributes:
      headline: 'Projetos Web'
      description: 'Confira as principais características de nossos layouts'
      layout: 'gantry-media://webproject-particle/layout.png'
      rightFeatures:
        -
          icon: 'fa fa-mobile'
          title: Responsivo
          description: 'simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the standard.'
        -
          icon: 'fa fa-search-plus'
          title: SEO
          description: 'simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the standard.'
        -
          icon: 'fa fa-trophy'
          title: Premiado
          description: 'simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the standard.'
      leftFeatures:
        -
          icon: 'fa fa-window-maximize'
          title: Customizável
          description: 'simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the standard.'
        -
          icon: 'fa fa-bolt'
          title: Rápido
          description: 'simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the standard.'
        -
          icon: 'fa fa-tasks'
          title: Gerenciável
          description: 'simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the standard.'
    block:
      variations: title2
  position-portfolio:
    attributes:
      key: portfolio
  position-team:
    attributes:
      key: team
  position-number:
    attributes:
      key: number
  position-info:
    attributes:
      key: info
  position-form:
    attributes:
      key: form
  branding-1577:
    block:
      class: wa-branding
  totop-5988:
    block:
      class: wa-totop
      variations: center
  copyright-8518:
    block:
      class: wa-copy
      variations: align-right
  mobile-menu-9282:
    title: 'Mobile Menu'
    block:
      class: wa-mobile-menu
