version: 2
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1506208974
layout:
  /top/:
    -
      - 'logo-4941 30'
      - 'menu-7382 70'
  /social/:
    -
      - social-8636
  /slider/:
    -
      - slider-5783
  /service/:
    -
      - position-service
  /web-project/:
    -
      - position-webproject
  /portfolio/:
    -
      - position-portfolio
  /team/:
    -
      - position-team
  /wrapper-bottom/:
    /number/:
      -
        - position-number
    /contact/:
      -
        - 'position-info 50'
        - 'position-form 50'
  /footer/:
    -
      - 'branding-6474 33.3'
      - 'totop-6520 33.3'
      - 'copyright-5659 33.3'
  offcanvas:
    -
      - mobile-menu-3590
structure:
  top:
    type: section
    subtype: header
    title: Topo
    attributes:
      boxed: ''
  social:
    type: section
    attributes:
      boxed: '3'
  slider:
    type: section
    title: SlideShow
    attributes:
      boxed: ''
  service:
    type: section
    title: Serviços
    attributes:
      boxed: ''
  web-project:
    type: section
    title: 'Projetos Web'
    attributes:
      boxed: ''
  portfolio:
    type: section
    attributes:
      boxed: ''
  team:
    type: section
    title: Equipe
    attributes:
      boxed: ''
  number:
    type: section
    title: Números
    attributes:
      boxed: ''
  contact:
    type: section
    title: Contato
    attributes:
      boxed: ''
  wrapper-bottom:
    attributes:
      name: Wrapper
      boxed: ''
  footer:
    title: Rodapé
    attributes:
      boxed: ''
content:
  logo-4941:
    block:
      class: wa-logo
  menu-7382:
    block:
      class: wa-menu
  social-8636:
    attributes:
      display: icons_only
      items:
        -
          icon: 'fa fa-twitter'
          text: Twitter
          link: 'http://twitter.com/leowg'
          name: Twitter
        -
          icon: 'fa fa-facebook'
          text: Facebook
          link: 'http://facebook.com/leowgweb'
          name: Facebook
        -
          icon: 'fa fa-google'
          text: Google
          link: 'http://plus.google.com/+leowgweb'
          name: Google
        -
          icon: 'fa fa-youtube'
          text: Youtube
          link: 'http://www.youtube.com/leowgweb'
          name: Youtube
    block:
      class:
        - 'wa-social hidden-phone'
      variations:
        - 'nopaddingall nomarginall'
  slider-5783:
    attributes:
      title1: '2 Descubra a Verdadeira Essência do Seu Projeto'
      title2: '50 Criatividade, Simplicidade e Inovação'
      title3: 'Deixe um brilho nos olhos de seus clientes ao apreciarem seu Projeto'
      imageOverlay: 'gantry-media://slider-particle/image-overlay.png'
      overlay: 'gantry-theme://js/vegas-background-slideshow/overlays/04.png'
      transition: zoomOut
      animation: random
      delay: '5000'
      transitionDuration: auto
      animationDuration: auto
      images:
        -
          title: 'Imagem 1'
          image: 'gantry-media://slider-particle/image1.jpg'
        -
          title: 'Imagem 2'
          image: 'gantry-media://slider-particle/image2.jpg'
        -
          title: 'Imagem 3'
          image: 'gantry-media://slider-particle/image3.jpg'
  position-service:
    attributes:
      key: service
  position-webproject:
    attributes:
      key: webproject
  position-portfolio:
    attributes:
      key: portfolio
  position-team:
    attributes:
      key: team
  position-number:
    attributes:
      key: number
  position-info:
    attributes:
      key: info
  position-form:
    attributes:
      key: form
  branding-6474:
    block:
      class: wa-branding
  totop-6520:
    block:
      class: wa-totop
      variations: center
  copyright-5659:
    block:
      class: wa-copy
      variations: align-right
  mobile-menu-3590:
    title: 'Mobile Menu'
    block:
      class: wa-mobile-menu
