name: _offline
timestamp: 1501715652
version: 7
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1501715651
positions:
  footer: Footer
sections:
  header: Header
  main: Main
  footer: Footer
particles:
  logo:
    logo-7421: Logo
  spacer:
    spacer-7287: Spacer
    spacer-6478: Spacer
  messages:
    system-messages-8707: 'System Messages'
  content:
    system-content-6386: 'Page Content'
  position:
    position-footer: Footer
  copyright:
    copyright-9124: Copyright
  branding:
    branding-1349: Branding
inherit: {  }
