version: 2
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1501715651
layout:
  /header/:
    -
      - 'logo-7421 30'
      - 'spacer-7287 70'
  /main/:
    -
      - system-messages-8707
    -
      - system-content-6386
  /footer/:
    -
      - position-footer
    -
      - 'copyright-9124 40'
      - 'spacer-6478 30'
      - 'branding-1349 30'
structure:
  header:
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
