version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1501715651
layout:
  /header/:
    -
      - 'logo-8031 30'
      - 'spacer-9044 70'
  /navigation/:
    -
      - menu-3534
  /main/:
    -
      - system-content-5300
  /footer/:
    -
      - position-footer
    -
      - 'copyright-6035 40'
      - 'spacer-7810 30'
      - 'branding-7691 30'
  offcanvas:
    -
      - mobile-menu-7906
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
